In [2]:
import pandas as pd

df = pd.read_csv("C:/Users/Santhoshkumar S/Desktop/Datascience/student_exam_performance.csv")

df.head()

,student_id,age,gender,education_level,school_type,family_income,parent_education,urban_rural,previous_exam_score,previous_gpa,...,exam_difficulty,exam_preparation_days,questions_attempted,questions_correct,time_management_score,exam_anxiety_level,exam_score,performance_grade,pass_status,performance_level
0,STU_000001,20,Female,High School,Public,Middle,NaN,Rural,78.36,2.95,...,Medium,27,95,86,NaN,9.39,90.40,A,Pass,High
1,STU_000002,17,Male,High School,Public,Middle,NaN,Suburban,73.40,2.89,...,Easy,4,100,86,87.17,6.31,86.21,A,Pass,High
2,STU_000003,18,Other,Undergraduate,Public,Middle,Master,Urban,82.76,3.35,...,Easy,28,96,74,63.77,9.87,76.11,B,Pass,Medium
3,STU_000004,20,Male,High School,Public,Middle,High School,Suburban,60.61,2.57,...,Medium,16,97,77,59.51,9.68,79.74,B,Pass,Medium
4,STU_000005,16,Female,High School,Private,High,Bachelor,Suburban,74.79,2.84,...,Medium,28,98,52,84.64,10.00,50.66,D,Pass,Low

In [3]:
df.loc[0]

student_id                     STU_000001
age                                    20
gender                             Female
education_level               High School
school_type                        Public
family_income                      Middle
parent_education                      NaN
urban_rural                         Rural
previous_exam_score                 78.36
previous_gpa                         2.95
attendance_percentage               81.49
assignment_completion_rate          65.18
class_participation                Medium
study_hours_per_day                  4.94
self_study_hours                     2.63
private_tuition                         0
online_learning_hours                1.75
study_consistency                  Medium
study_environment                Moderate
study_method                   Flashcards
revision_frequency                 Rarely
practice_tests_completed                8
notes_quality                     Average
sleep_hours                          6.31
sleep_quality                   Excellent
daily_screen_time                     3.8
physical_activity_hours              0.93
break_frequency                Frequently
stress_level                           10
motivation_level                     High
internet_access                         1
device_availability                Shared
educational_app_usage                 Low
online_course_hours                  2.15
exam_difficulty                    Medium
exam_preparation_days                  27
questions_attempted                    95
questions_correct                      86
time_management_score                 NaN
exam_anxiety_level                   9.39
exam_score                           90.4
performance_grade                       A
pass_status                          Pass
performance_level                    High
Name: 0, dtype: object

In [4]:
df.loc[0:19]

,student_id,age,gender,education_level,school_type,family_income,parent_education,urban_rural,previous_exam_score,previous_gpa,...,exam_difficulty,exam_preparation_days,questions_attempted,questions_correct,time_management_score,exam_anxiety_level,exam_score,performance_grade,pass_status,performance_level
0,STU_000001,20,Female,High School,Public,Middle,NaN,Rural,78.36,2.95,...,Medium,27,95,86,NaN,9.39,90.40,A,Pass,High
1,STU_000002,17,Male,High School,Public,Middle,NaN,Suburban,73.40,2.89,...,Easy,4,100,86,87.17,6.31,86.21,A,Pass,High
2,STU_000003,18,Other,Undergraduate,Public,Middle,Master,Urban,82.76,3.35,...,Easy,28,96,74,63.77,9.87,76.11,B,Pass,Medium
3,STU_000004,20,Male,High School,Public,Middle,High School,Suburban,60.61,2.57,...,Medium,16,97,77,59.51,9.68,79.74,B,Pass,Medium
4,STU_000005,16,Female,High School,Private,High,Bachelor,Suburban,74.79,2.84,...,Medium,28,98,52,84.64,10.00,50.66,D,Pass,Low
5,STU_000006,18,Male,High School,Public,High,High School,Rural,67.68,NaN,...,Hard,27,96,65,55.27,6.12,67.90,C,Pass,Medium
6,STU_000007,18,Male,High School,Charter,Middle,NaN,Urban,78.84,3.00,...,Hard,12,98,54,86.15,9.46,53.86,D,Pass,Low
7,STU_000008,20,Female,Undergraduate,Private,Lower-Middle,Bachelor,Suburban,90.79,3.63,...,Easy,7,94,91,88.08,10.00,97.61,A,Pass,High
8,STU_000009,15,Male,Undergraduate,Public,Lower-Middle,Associate,Suburban,61.28,2.43,...,Hard,14,94,35,70.21,8.34,34.44,F,Fail,Low
9,STU_000010,16,Female,Undergraduate,Public,Lower-Middle,Associate,Rural,61.33,2.72,...,Hard,4,87,34,73.78,8.49,39.05,F,Fail,Low
10,STU_000011,20,Male,High School,Private,Middle,Doctorate,Suburban,71.70,2.86,...,Medium,2,93,68,NaN,4.59,76.22,B,Pass,Medium
11,STU_000012,16,Male,High School,Public,Upper-Middle,Associate,Urban,94.04,3.85,...,Medium,3,94,74,89.89,10.00,77.19,B,Pass,Medium
12,STU_000013,16,Female,Undergraduate,Public,Middle,Associate,Urban,77.31,3.14,...,Easy,11,98,62,63.69,9.32,60.24,D,Pass,Medium
13,STU_000014,18,Female,High School,Private,Lower-Middle,NaN,Suburban,67.88,2.64,...,Hard,24,94,58,100.00,7.10,61.67,D,Pass,Medium
14,STU_000015,17,Male,High School,Public,Middle,Associate,Suburban,71.90,2.70,...,Medium,26,94,72,76.86,10.00,75.29,B,Pass,Medium
15,STU_000016,16,Male,High School,Public,Middle,Bachelor,Rural,41.12,1.83,...,Hard,14,93,36,96.84,8.47,38.77,F,Fail,Low
16,STU_000017,19,Male,High School,Public,Middle,Bachelor,Rural,75.61,3.12,...,Medium,17,87,77,91.31,10.00,86.36,A,Pass,High
17,STU_000018,18,Male,Undergraduate,Public,Middle,High School,Suburban,73.86,NaN,...,Hard,11,92,52,NaN,8.43,55.88,D,Pass,Low
18,STU_000019,15,Female,High School,Public,Low,Master,Suburban,52.90,2.03,...,Hard,3,100,30,NaN,9.85,32.50,F,Fail,Low
19,STU_000020,17,Female,High School,Private,Lower-Middle,Associate,Urban,87.54,3.52,...,Medium,28,93,64,81.07,10.00,70.56,C,Pass,Medium

In [5]:
df.iloc[0:10, 0:5]

   student_id  age  gender education_level school_type
0  STU_000001   20  Female     High School      Public
1  STU_000002   17    Male     High School      Public
2  STU_000003   18   Other   Undergraduate      Public
3  STU_000004   20    Male     High School      Public
4  STU_000005   16  Female     High School     Private
5  STU_000006   18    Male     High School      Public
6  STU_000007   18    Male     High School     Charter
7  STU_000008   20  Female   Undergraduate     Private
8  STU_000009   15    Male   Undergraduate      Public
9  STU_000010   16  Female   Undergraduate      Public

In [9]:
df[df["exam_score"] > 50]

df[df["exam_score"] < 50]

df[df["exam_score"] >= 50]

df[df["exam_score"] <= 50]

df[(df["exam_score"] > 50) & (df["study_hours_per_day"] > 2)]

df[(df["exam_score"] > 50) | (df["study_hours_per_day"] > 2)]

df[~(df["exam_score"] > 50)]

,student_id,age,gender,education_level,school_type,family_income,parent_education,urban_rural,previous_exam_score,previous_gpa,...,exam_difficulty,exam_preparation_days,questions_attempted,questions_correct,time_management_score,exam_anxiety_level,exam_score,performance_grade,pass_status,performance_level
8,STU_000009,15,Male,Undergraduate,Public,Lower-Middle,Associate,Suburban,61.28,2.43,...,Hard,14,94,35,70.21,8.34,34.44,F,Fail,Low
9,STU_000010,16,Female,Undergraduate,Public,Lower-Middle,Associate,Rural,61.33,2.72,...,Hard,4,87,34,73.78,8.49,39.05,F,Fail,Low
15,STU_000016,16,Male,High School,Public,Middle,Bachelor,Rural,41.12,1.83,...,Hard,14,93,36,96.84,8.47,38.77,F,Fail,Low
18,STU_000019,15,Female,High School,Public,Low,Master,Suburban,52.90,2.03,...,Hard,3,100,30,NaN,9.85,32.50,F,Fail,Low
22,STU_000023,15,Male,High School,Public,Low,High School,Suburban,63.72,2.42,...,Medium,1,90,18,78.70,8.43,19.76,F,Fail,Low
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99954,STU_099955,19,Female,High School,Public,Upper-Middle,Doctorate,Urban,57.82,2.38,...,Hard,3,87,40,61.86,9.89,44.59,F,Fail,Low
99960,STU_099961,17,Female,Undergraduate,Public,Lower-Middle,Bachelor,Suburban,68.83,2.82,...,Medium,22,92,39,58.95,9.95,43.61,F,Fail,Low
99968,STU_099969,16,Male,Undergraduate,Public,Middle,NaN,Urban,71.27,NaN,...,Medium,1,95,40,88.93,10.00,45.51,F,Fail,Low
99976,STU_099977,16,Male,High School,Public,Middle,High School,Rural,50.49,2.26,...,Medium,15,93,37,NaN,10.00,38.78,F,Fail,Low
99994,STU_099995,15,Male,High School,Public,Low,Associate,Urban,54.37,2.13,...,Easy,5,97,39,79.83,10.00,40.70,F,Fail,Low

In [8]:
print(df.columns)

Index(['student_id', 'age', 'gender', 'education_level', 'school_type',
       'family_income', 'parent_education', 'urban_rural',
       'previous_exam_score', 'previous_gpa', 'attendance_percentage',
       'assignment_completion_rate', 'class_participation',
       'study_hours_per_day', 'self_study_hours', 'private_tuition',
       'online_learning_hours', 'study_consistency', 'study_environment',
       'study_method', 'revision_frequency', 'practice_tests_completed',
       'notes_quality', 'sleep_hours', 'sleep_quality', 'daily_screen_time',
       'physical_activity_hours', 'break_frequency', 'stress_level',
       'motivation_level', 'internet_access', 'device_availability',
       'educational_app_usage', 'online_course_hours', 'exam_difficulty',
       'exam_preparation_days', 'questions_attempted', 'questions_correct',
       'time_management_score', 'exam_anxiety_level', 'exam_score',
       'performance_grade', 'pass_status', 'performance_level'],
      dtype='str')

In [ ]:
df.sort_values(by="exam_score", ascending=True)

df.sort_values(by="exam_score", ascending=False)

df.sort_values(by=["gender", "exam_score"], ascending=[True, False])